Task: vocal_fold
TrainingFraction:
- 0.95
alphavalue: 0.7
batch_size: 4
bodyparts:
- AC
- LC1
- LC2
- LC3
- LC4
- LC5
- LVP
- RC1
- RC2
- RC3
- RC4
- RC5
- RVP
colormap: jet
corner2move2:
- 50
- 50
cropping: false
date: Aug7
dotsize: 4
iteration: 2
move2corner: true
numframes2pick: 20
pcutoff: 0.1
project_path: D:\Python Workspace\Projects\VCTrack\vocal_fold-Nat-2019-08-07
resnet: 50
scorer: Nat
skeleton: []
skeleton_color: black
snapshotindex: -1
start: 0
stop: 1
video_sets:
  C:\Users\NA659\Desktop\test_vids\vocal.mp4:
    crop: 0, 480, 0, 360
  C:\Users\NA659\Desktop\test_vids\vocal0_resized.mp4:
    crop: 0, 640, 0, 360
  C:\Users\NA659\Desktop\test_vids\vocal0_resizedwith_lines.mp4:
    crop: 0, 640, 0, 360
  C:\Users\NA659\Desktop\test_vids\vocalwith_lines.mp4:
    crop: 0, 480, 0, 360
  C:\Users\NA659\Documents\Mau Vids\002B_resized.mp4:
    C:\Users\NA659\Documents\test_vids\nop10.mp4: null
    crop: 0, 640, 0, 360
  C:\Users\NA659\Documents\Mau Vids\004E.mp4:
    crop: 0, 640, 0, 360
  C:\Users\NA659\Documents\Mau Vids\005D.mp4:
    crop: 0, 640, 0, 360
  C:\Users\NA659\Documents\Mau Vids\007C.mp4:
    crop: 0, 640, 0, 360
  C:\Users\NA659\Documents\test_vids\nop1.mp4:
    crop: 0, 640, 0, 360
  C:\Users\NA659\Documents\test_vids\nop11.mp4:
    crop: 0, 640, 0, 360
  C:\Users\NA659\Documents\test_vids\nop12.mp4:
    crop: 0, 640, 0, 360
  C:\Users\NA659\Documents\test_vids\nop13.mp4:
    crop: 0, 640, 0, 360
  C:\Users\NA659\Documents\test_vids\nop14.mp4:
    crop: 0, 640, 0, 360
  C:\Users\NA659\Documents\test_vids\nop15.mp4:
    crop: 0, 640, 0, 360
  C:\Users\NA659\Documents\test_vids\nop19.mp4:
    crop: 0, 640, 0, 360
  C:\Users\NA659\Documents\test_vids\nop2.mp4:
    crop: 0, 640, 0, 360
  C:\Users\NA659\Documents\test_vids\nop20.mp4:
    crop: 0, 640, 0, 360
  C:\Users\NA659\Documents\test_vids\nop3.mp4:
    crop: 0, 640, 0, 360
  C:\Users\NA659\Documents\test_vids\nop4.mp4:
    crop: 0, 640, 0, 360
  C:\Users\NA659\Documents\test_vids\nop5.mp4:
    crop: 0, 640, 0, 360
  C:\Users\NA659\Documents\test_vids\nop6.mp4:
    crop: 0, 640, 0, 360
  C:\Users\NA659\Documents\test_vids\nop7.mp4:
    crop: 0, 640, 0, 360
  C:\Users\NA659\Documents\test_vids\nop8.mp4:
    crop: 0, 640, 0, 360
  C:\Users\NA659\Documents\test_vids\nop9.mp4:
    crop: 0, 640, 0, 360
  C:\Users\NA659\Documents\test_vids\uvfp1.mp4:
    crop: 0, 640, 0, 360
  C:\Users\NA659\Documents\test_vids\uvfp10.mp4:
    crop: 0, 640, 0, 360
  C:\Users\NA659\Documents\test_vids\uvfp11.mp4:
    crop: 0, 640, 0, 360
  C:\Users\NA659\Documents\test_vids\uvfp12.mp4:
    crop: 0, 640, 0, 360
  C:\Users\NA659\Documents\test_vids\uvfp13.mp4:
    crop: 0, 720, 0, 480
  C:\Users\NA659\Documents\test_vids\uvfp14.mp4:
    crop: 0, 640, 0, 360
  C:\Users\NA659\Documents\test_vids\uvfp15.mp4:
    crop: 0, 640, 0, 360
  C:\Users\NA659\Documents\test_vids\uvfp2.mp4:
    crop: 0, 640, 0, 360
  C:\Users\NA659\Documents\test_vids\uvfp20.mp4:
    crop: 0, 640, 0, 360
  C:\Users\NA659\Documents\test_vids\uvfp3.mp4:
    crop: 0, 640, 0, 360
  C:\Users\NA659\Documents\test_vids\uvfp4.mp4:
    crop: 0, 640, 0, 360
  C:\Users\NA659\Documents\test_vids\uvfp5.mp4:
    crop: 0, 640, 0, 360
  C:\Users\NA659\Documents\test_vids\uvfp6.mp4:
    crop: 0, 640, 0, 360
  C:\Users\NA659\Documents\test_vids\uvfp7.mp4:
    crop: 0, 640, 0, 360
  C:\Users\NA659\Documents\test_vids\uvfp8.mp4:
    crop: 0, 640, 0, 360
  C:\Users\NA659\Documents\test_vids\uvfp9.mp4:
    crop: 0, 640, 0, 360
  D:\MovedDownload\test_vids\nop10.mp4:
    crop: 0, 640, 0, 480
  D:\MovedDownload\test_vids\nop3.mp4:
    crop: 0, 640, 0, 480
  D:\MovedDownload\test_vids\uvfp7.mp4:
    crop: 0, 640, 0, 480
x1: 0
x2: 640
y1: 277
y2: 624
